import { Course, CourseModule } from "@/types/course";

export const courses: Course[] = [
  {
    id: "01-01",
    title: "冯诺依曼架构：计算机的「大脑」是怎么工作的",
    slug: "von-neumann-architecture",
    description: "从厨房工作流程理解计算机的五大组成部分，揭开计算机工作的神秘面纱",
    module: "01-computer-basics",
    moduleName: "计算机基础",
    moduleOrder: 1,
    lessonOrder: 1,
    difficulty: 1,
    durationMinutes: 20,
    prerequisites: [],
    tags: ["computer-architecture", "von-neumann", "basics"],
    author: "cs-professor",
    createdAt: "2026-05-03",
    updatedAt: "2026-05-03",
    status: "published",
  },
  {
    id: "01-02",
    title: "CPU：计算机的「厨师长」",
    slug: "cpu-basics",
    description: "深入理解CPU的工作原理，时钟、指令、运算，一网打尽",
    module: "01-computer-basics",
    moduleName: "计算机基础",
    moduleOrder: 1,
    lessonOrder: 2,
    difficulty: 2,
    durationMinutes: 25,
    prerequisites: ["01-01"],
    tags: ["cpu", "processor", "computer-architecture"],
    author: "cs-professor",
    createdAt: "2026-05-03",
    updatedAt: "2026-05-03",
    status: "draft",
  },
  {
    id: "01-03",
    title: "内存：计算机的「工作台」",
    slug: "memory-basics",
    description: "理解内存的层次结构，从寄存器到硬盘，速度vs容量的权衡",
    module: "01-computer-basics",
    moduleName: "计算机基础",
    moduleOrder: 1,
    lessonOrder: 3,
    difficulty: 2,
    durationMinutes: 25,
    prerequisites: ["01-01", "01-02"],
    tags: ["memory", "ram", "cache", "storage"],
    author: "cs-professor",
    createdAt: "2026-05-03",
    updatedAt: "2026-05-03",
    status: "draft",
  },
  {
    id: "02-01",
    title: "数组：排好队的数据",
    slug: "arrays",
    description: "最基础的数据结构，理解连续内存存储的优缺点",
    module: "02-data-structures",
    moduleName: "数据结构",
    moduleOrder: 2,
    lessonOrder: 1,
    difficulty: 1,
    durationMinutes: 20,
    prerequisites: [],
    tags: ["array", "data-structure", "basics"],
    author: "cs-professor",
    createdAt: "2026-05-03",
    updatedAt: "2026-05-03",
    status: "draft",
  },
  {
    id: "02-02",
    title: "链表：手拉手的数据",
    slug: "linked-lists",
    description: "灵活的数据结构，动态扩容的秘密武器",
    module: "02-data-structures",
    moduleName: "数据结构",
    moduleOrder: 2,
    lessonOrder: 2,
    difficulty: 2,
    durationMinutes: 25,
    prerequisites: ["02-01"],
    tags: ["linked-list", "data-structure", "pointer"],
    author: "cs-professor",
    createdAt: "2026-05-03",
    updatedAt: "2026-05-03",
    status: "draft",
  },
  {
    id: "02-03",
    title: "栈和队列：两种排队方式",
    slug: "stacks-and-queues",
    description: "后进先出vs先进先出，生活中的数据结构",
    module: "02-data-structures",
    moduleName: "数据结构",
    moduleOrder: 2,
    lessonOrder: 3,
    difficulty: 2,
    durationMinutes: 25,
    prerequisites: ["02-02"],
    tags: ["stack", "queue", "data-structure"],
    author: "cs-professor",
    createdAt: "2026-05-03",
    updatedAt: "2026-05-03",
    status: "draft",
  },
  {
    id: "03-01",
    title: "排序算法：让数据井然有序",
    slug: "sorting-algorithms",
    description: "冒泡、选择、插入、快速排序，一网打尽",
    module: "03-algorithms",
    moduleName: "算法",
    moduleOrder: 3,
    lessonOrder: 1,
    difficulty: 2,
    durationMinutes: 30,
    prerequisites: ["02-01"],
    tags: ["sorting", "algorithm", "bubble-sort", "quick-sort"],
    author: "cs-professor",
    createdAt: "2026-05-03",
    updatedAt: "2026-05-03",
    status: "draft",
  },
  {
    id: "03-02",
    title: "查找算法：大海捞针有妙招",
    slug: "searching-algorithms",
    description: "线性查找、二分查找，效率差异有多大",
    module: "03-algorithms",
    moduleName: "算法",
    moduleOrder: 3,
    lessonOrder: 2,
    difficulty: 2,
    durationMinutes: 25,
    prerequisites: ["03-01"],
    tags: ["searching", "algorithm", "binary-search"],
    author: "cs-professor",
    createdAt: "2026-05-03",
    updatedAt: "2026-05-03",
    status: "draft",
  },
];

export const modules: CourseModule[] = [
  {
    id: "01-computer-basics",
    name: "计算机基础",
    description: "从冯诺依曼架构开始，理解计算机的基本工作原理",
    order: 1,
    courseCount: 5,
    courses: courses.filter((c) => c.module === "01-computer-basics"),
  },
  {
    id: "02-data-structures",
    name: "数据结构",
    description: "数组、链表、栈、队列、树、图，数据结构全解析",
    order: 2,
    courseCount: 8,
    courses: courses.filter((c) => c.module === "02-data-structures"),
  },
  {
    id: "03-algorithms",
    name: "算法",
    description: "排序、查找、递归、动态规划，算法思维养成",
    order: 3,
    courseCount: 10,
    courses: courses.filter((c) => c.module === "03-algorithms"),
  },
  {
    id: "04-operating-systems",
    name: "操作系统",
    description: "进程、线程、内存管理、文件系统",
    order: 4,
    courseCount: 6,
    courses: [],
  },
  {
    id: "05-databases",
    name: "数据库",
    description: "SQL基础、索引、事务、优化",
    order: 5,
    courseCount: 5,
    courses: [],
  },
  {
    id: "06-networks",
    name: "计算机网络",
    description: "TCP/IP、HTTP、DNS、WebSocket",
    order: 6,
    courseCount: 5,
    courses: [],
  },
  {
    id: "07-programming",
    name: "编程语言",
    description: "Python、Go、TypeScript、Rust",
    order: 7,
    courseCount: 5,
    courses: [],
  },
  {
    id: "08-ai-ml",
    name: "AI/ML基础",
    description: "机器学习、神经网络、大模型",
    order: 8,
    courseCount: 3,
    courses: [],
  },
  {
    id: "09-web-development",
    name: "Web开发",
    description: "前端基础、后端API设计",
    order: 9,
    courseCount: 2,
    courses: [],
  },
  {
    id: "10-system-design",
    name: "系统架构",
    description: "微服务、分布式基础",
    order: 10,
    courseCount: 1,
    courses: [],
  },
];

export function getCourseBySlug(slug: string): Course | undefined {
  return courses.find((course) => course.slug === slug);
}

export function getCoursesByModule(moduleId: string): Course[] {
  return courses.filter((course) => course.module === moduleId);
}

export function getAllCourses(): Course[] {
  return courses;
}

export function getAllModules(): CourseModule[] {
  return modules;
}

export function getPublishedCourses(): Course[] {
  return courses.filter((course) => course.status === "published");
}
